### ISSUE TITLE
No Hover hints , diagnostics and others

### ISSUE THREAD

**Issue by zle000** [profelis/daScript-plugin#12]
I have set daScript path int setting,but it seems not work for me.... 
I think the “**server.das**” take so much time to compile for run。。。

**Comment by zle000** [comment]
I set the connectTimeout to 50s,and it working...

**Comment by profelis** [comment]
It hard to believe, but this is easiest fix. I didn’t managed to fix it more correctly. Try to find lowest timeout then all works and use it. For debug build it usually 20-30sec, for “release with debug info” - 4-8

**Comment by zle000** [comment]
ok, that works ok~
