### ISSUE TITLE
It seems that the plugin is running slowly..

### ISSUE THREAD

**Issue by zle000** [profelis/daScript-plugin#13]
It seems that the plugin is running slowly, and the error diagnostics and prompts are slow to respond when writing code. How to  improve the plugin efficiency?

**Comment by profelis** [comment]
Use release or relWithDebugInfo build for plugin. Not debug. You always can set different executable for plugin and for regular development

**Comment by zle000** [comment]
> Use release or relWithDebugInfo build for plugin. Not debug. You always can set different executable for plugin and for regular development

emmm... Change to release is better,but some time there no  prompts or wrong tip~~

**Comment by profelis** [comment]
Plugin uses compiler to show hints. when some vars are dropped as unused or you have errors in the code plugin doesn’t work correctly. Can you create small example when really exists problem? Because now I don’t know how to help
