### ISSUE TITLE
The Variables not show~

### ISSUE THREAD

**Issue by zle000** [profelis/daScript-plugin#14]
Did I configure something wrong or else ？
![2024-03-29 180104](https://github.com/profelis/daScript-plugin/assets/94626515/bc548ca7-83d2-475f-a635-72e4109a6c7d)

**Comment by profelis** [comment]
All is correct. All this variables are inlined or dropped as unused and without sideeffects. Add debug print with all this vars and you will get them in debugger

**Comment by zle000** [comment]
> All is correct. All this variables are inlined or dropped as unused and without sideeffects. Add debug print with all this vars and you will get them in debugger

oh~~  cool~
