### ISSUE TITLE
How to get code hints or auto-completion for bound C++ modules?

### ISSUE THREAD

**Issue by zle000** [profelis/daScript-plugin#15]
For example：
```
require TestModule

[export]
def main
    TestModuleFunc("hi")
```
Would it be possible to receive prompts for the bound function TestModuleFunc ?

**Comment by profelis** [comment]
you need console utility (like [dascript](https://github.com/GaijinEntertainment/daScript/blob/master/utils/daScript/main.cpp)) or something like this compiled with all your modules and which able to run language server. Usually it's exactly dascript.exe but with additional NEED_MODULE(...) calls, to pull your specific modules.
