### ISSUE TITLE
The error tip not updated when change code text.

### ISSUE THREAD

**Issue by zle000** [profelis/daScript-plugin#24]
A file with a function 
`def sdf() 
    return 100`

B file call this function like this:
`sdf("hi")`
this is a error,so I chang the function in A file to add string arg,but B file the error tip not disappear, I need type somgthing so it be ok~

**Comment by profelis** [comment]
Hi! Thanks for your report, I know about this issue and I'll fix it later

**Comment by profelis** [comment]
should be fixed in 1.1.13
