### ISSUE TITLE
Curious miscast error

### ISSUE THREAD

**Issue by madwareru** [profelis/daScript-plugin#4]
In a v0.10.7 I see this error:
![изображение](https://user-images.githubusercontent.com/29083023/155159257-aa7884cc-baf2-459c-85cf-1c9ac215c34d.png)

**Comment by profelis** [comment]
Hi! update dascript to latest version or downgrade plugin to previous

Here was breaking change https://github.com/GaijinEntertainment/daScript/commit/c3f5751758b8cda6a4abe7466d9402bcd77bae75
