### ISSUE TITLE
Unexpected plugin disconecting

### ISSUE THREAD

**Issue by DVAV23** [profelis/daScript-plugin#9]
If you connect this plugin to a file with a piece of this code, then everything is fine.
```
struct LinkedList
   data: int
   next_node: LinkedList? 

var linkedList = new [[LinkedList ]]
```
But if you replace `next_node: LinkedList?` to `next_node: LinkedList` (remove **?**), then plugin will be disconected and not reconnected after restart.

**Comment by profelis** [comment]
Hi! we are still working on this error, problem is inside dascript compiler.

**Comment by profelis** [comment]
fixed, update dascript please

https://github.com/GaijinEntertainment/daScript/pull/655
